"""TDB-AM Session:Start Persona Hook.

On every new session, calls TDB-AM /recall to fetch the user's persona,
scene context, and relevant memories, then writes them to a file for the
tdb-memory skill to inject into the agent's system prompt.

Falls back gracefully if TDB-AM is unreachable or returns no memories.
"""

import asyncio
import json
import logging
import os
import pathlib
import re
from urllib.request import Request, urlopen
from urllib.error import URLError

logger = logging.getLogger("hooks.tdb-persona")

TDB_RECALL_URL = "http://localhost:8420/recall"
PERSONA_DIR = pathlib.Path(os.path.expanduser("~/.hermes/data/tdai-memory/persona"))


def _safe_key(s: str) -> str:
    """Sanitize a string for filesystem safety."""
    return "".join(c if c.isalnum() or c in "-_" else "_" for c in s)


def _fetch_recall(session_key: str) -> dict | None:
    """Synchronous fetch from TDB-AM /recall. Returns parsed JSON or None."""
    try:
        payload = json.dumps({"query": "session start", "session_key": session_key}).encode("utf-8")
        req = Request(TDB_RECALL_URL, data=payload, headers={"Content-Type": "application/json"}, method="POST")
        with urlopen(req, timeout=8) as resp:
            if resp.status != 200:
                logger.debug("TDB recall: HTTP %d for %s", resp.status, session_key)
                return None
            return json.loads(resp.read().decode("utf-8"))
    except URLError as e:
        logger.debug("TDB recall unreachable: %s", e)
    except Exception as e:
        logger.debug("TDB recall error: %s", e)
    return None


def _write_persona(session_key: str, recall_data: dict) -> bool:
    """Write persona file. Returns True if meaningful content was written."""
    memory_count = recall_data.get("memory_count", 0)
    context = recall_data.get("context", "")

    if memory_count == 0 and not context.strip():
        return False

    PERSONA_DIR.mkdir(parents=True, exist_ok=True)
    persona_path = PERSONA_DIR / f"{session_key}.md"

    # Strip HTML-like wrapper tags for cleaner markdown
    clean = re.sub(r"</?memory-tools-guide>", "", context)
    clean = re.sub(r"</?user-persona>", "", clean)
    clean = re.sub(r"</?scene-navigation>", "", clean)

    content = f"<!-- TDB-AM Persona Snapshot for session_key={session_key} -->\n"
    content += f"<!-- memory_count={memory_count}, auto-generated by tdb-persona hook -->\n\n"
    content += clean.strip() + "\n"

    persona_path.write_text(content, encoding="utf-8")
    logger.info("TDB persona written: %s (%d memories)", persona_path, memory_count)
    return True


async def handle(event_type: str, context: dict) -> None:
    """Fetch persona on session start."""
    platform = context.get("platform", "unknown")
    user_id = context.get("user_id", "anon")
    session_key = context.get("session_key", f"{_safe_key(platform)}-{_safe_key(str(user_id))}")

    # Fallback: build session_key from platform + user_id if not in context
    if not context.get("session_key"):
        session_key = f"{_safe_key(platform)}-{_safe_key(str(user_id))}"

    # Run in executor thread to avoid blocking event loop
    loop = asyncio.get_running_loop()
    recall_data = await loop.run_in_executor(None, _fetch_recall, session_key)

    if recall_data is None:
        return  # TDB-AM unreachable — silent fallback

    await loop.run_in_executor(None, _write_persona, session_key, recall_data)
